# https://taskfile.dev

version: "3"

env:
  PYTHON_SRC: pylode
  TESTS_DIR: tests

tasks:
  install:
    cmds:
      - uv sync

  format:
    desc: Format Python code.
    cmds:
      - uv run ruff format $PYTHON_SRC
      - uv run ruff check --select I --fix $PYTHON_SRC
      - uv run ruff format $TESTS_DIR
      - uv run ruff check --select I --fix $TESTS_DIR

  test:
    desc: Run tests
    cmds:
      - uv run pytest tests -rP -W "ignore:ConjunctiveGraph is deprecated, use Dataset instead.:DeprecationWarning:rdflib.plugins.parsers.jsonld" -W "ignore:There is no current event loop:DeprecationWarning:dominate.dom_tag"
