# Run the SuperLinter action with some custom setup.

name: Lint

on:
  push:
    branches: ["2.x"]
  pull_request:
    branches: ["2.x"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Super-Linter
        uses: github/super-linter@v3.15.5
        env:
          VALIDATE_MARKDOWN: false
          # Disabled for conflicts with the isort version used in pre-commit
          #   you can re-enable it if you align your local isort with
          #   the one in the super-linter image.
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_XML: false
          VALIDATE_NATURAL_LANGUAGE: false
